#!/bin/bash
max=""
min=""

for i in {1..5}
do
        read -p "Enter your number $i: " input

        if [ -z $max ]
        then
                max=$input
                min=$input
        fi

        if [ $input -lt $min ]
        then
                max=$input
        elif [ $input -gt $max ]
        then
                max=$input
        fi
        let sum="$sum"+"$input"
done
echo "$max is biggest."
echo "$min is smallest."
echo "$sum is Sum."
sum=$((sum/i))
echo "$sum is avg."

