#!/bin/bash

ping -c 2 "$1" >> /dev/null 2>&1

if [ $? -eq 0 ]; then
        sshpass -p "$3" scp -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" /etc/passwd "$2"@"$1":/etc/pass
else
        echo "The server is not accessible."
fi

#As far as I understood, SSH only accepts passwords via keyboard so I had to use "sshpass".

#Gets IP, Username and Password along script name as values, ping IP, if pingable, copies /etc/passwd to /home/user/ of destination IP. If not pingable says no accessible.
