#!/bin/bash

awk -F: '{ print $1"....."$3 }' /etc/passwd > /home/"$USER"/`date +%y%m%d`

find /home/"$USER" -type f -name "[0-9][0-9][0-9][0-9][0-9][0-9]" -mtime +2 -exec rm {} \;

at now + 24 hours <<EOT
/home/wtf/ex5
EOT

#Saves first and third fields of /etc/passwd everyday in a file, named same date and delete it after 2 days.
